@@include('libs/smoothScroll.js', {})
@@include('libs/inputmask.min.js', {})
@@include('libs/swiper-bundle.min.js', {})
@@include('libs/nouislider.js', {})
@@include('libs/wNumb.min.js', {})
@@include('libs/lightgallery.min.js', {})
@@include('libs/tippy.js', {})
@@include('libs/datepicker-full.min.js', {})